USE [Milestone3]
GO

/****** Object:  Table [dbo].[CelBodTYPE]    Script Date: 2/29/2024 12:49:01 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CelBodTYPE](
	[CelBodyTypeID] [int] IDENTITY(1,1) NOT NULL,
	[CelBodyTypeName] [varchar](30) NULL,
	[HabID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CelBodyTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CelBodTYPE]  WITH CHECK ADD FOREIGN KEY([HabID])
REFERENCES [dbo].[HABITABILITY] ([HabID])
GO

USE [Milestone3]
GO

/****** Object:  Table [dbo].[CELESTIALBODY]    Script Date: 2/29/2024 12:49:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CELESTIALBODY](
	[CelBodyID] [int] IDENTITY(1,1) NOT NULL,
	[CelBodyName] [varchar](30) NULL,
	[Mass] [decimal](10, 3) NULL,
	[Radius] [decimal](10, 3) NULL,
	[OrbitalDistance] [decimal](10, 3) NULL,
	[OSystemID] [int] NULL,
	[CelBodyTypeID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CelBodyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CELESTIALBODY]  WITH CHECK ADD FOREIGN KEY([CelBodyTypeID])
REFERENCES [dbo].[CelBodTYPE] ([CelBodyTypeID])
GO

ALTER TABLE [dbo].[CELESTIALBODY]  WITH CHECK ADD FOREIGN KEY([OSystemID])
REFERENCES [dbo].[ORBITALSYSTEM] ([OrbSysID])
GO

USE [Milestone3]
GO

/****** Object:  Table [dbo].[DBUSER]    Script Date: 2/29/2024 12:49:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DBUSER](
	[UID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [char](32) NOT NULL,
	[Email] [char](64) NOT NULL,
	[PasswordHash] [varchar](80) NULL,
	[Clearance] [int] NOT NULL,
	[FacID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DBUSER]  WITH CHECK ADD FOREIGN KEY([FacID])
REFERENCES [dbo].[FACTION] ([FacID])
GO

USE [Milestone3]
GO

/****** Object:  Table [dbo].[FACTION]    Script Date: 2/29/2024 1:10:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACTION](
	[FacID] [int] IDENTITY(1,1) NOT NULL,
	[FactionName] [varchar](32) NULL,
PRIMARY KEY CLUSTERED 
(
	[FacID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Milestone3]
GO

/****** Object:  Table [dbo].[FACTIONCONTROLS]    Script Date: 2/29/2024 1:10:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACTIONCONTROLS](
	[FacID] [int] IDENTITY(1,1) NOT NULL,
	[CBID] [int] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FACTIONCONTROLS]  WITH CHECK ADD FOREIGN KEY([FacID])
REFERENCES [dbo].[FACTION] ([FacID])
GO

ALTER TABLE [dbo].[FACTIONCONTROLS]  WITH CHECK ADD FOREIGN KEY([CBID])
REFERENCES [dbo].[CELESTIALBODY] ([CelBodyID])
GO

USE [Milestone3]
GO

/****** Object:  Table [dbo].[HABITABILITY]    Script Date: 2/29/2024 1:10:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HABITABILITY](
	[HabID] [int] IDENTITY(1,1) NOT NULL,
	[HabName] [varchar](24) NULL,
	[Colonizable] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[HabID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Milestone3]
GO

/****** Object:  Table [dbo].[ORBITALSYSTEM]    Script Date: 2/29/2024 1:10:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ORBITALSYSTEM](
	[OrbSysID] [int] IDENTITY(1,1) NOT NULL,
	[OrbSysName] [varchar](24) NULL,
	[CelBodyID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OrbSysID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORBITALSYSTEM]  WITH CHECK ADD FOREIGN KEY([CelBodyID])
REFERENCES [dbo].[CELESTIALBODY] ([CelBodyID])
GO

USE [Milestone3]
GO

/****** Object:  Table [dbo].[SAVED]    Script Date: 2/29/2024 1:11:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SAVED](
	[UID] [int] IDENTITY(1,1) NOT NULL,
	[CelBodyID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UID] ASC,
	[CelBodyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SAVED]  WITH CHECK ADD FOREIGN KEY([CelBodyID])
REFERENCES [dbo].[CELESTIALBODY] ([CelBodyID])
GO

ALTER TABLE [dbo].[SAVED]  WITH CHECK ADD FOREIGN KEY([UID])
REFERENCES [dbo].[DBUSER] ([UID])
GO


