USE Milestone3
DELETE FROM CelBodTYPE;
DELETE FROM CELESTIALBODY;
DELETE FROM DBUSER;
DELETE FROM FACTION;
DELETE FROM FACTIONCONTROLS;
DELETE FROM HABITABILITY;
DELETE FROM ORBITALSYSTEM;
DELETE FROM SAVED;